Include jakarta.servlet-api in the shaded lite jar
Fixes Kustvakt lite startup

Error: Unable to initialize main class
de.ids_mannheim.korap.server.KustvaktLiteServer
Caused by: java.lang.NoClassDefFoundError: jakarta/servlet/Servlet

Change-Id: Idf31e9f14754a5ec2a36c28e6884685593cd5519